version: "3.8"
services:
  rustart-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - rustart-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  rustart-minio:
    image: minio/minio:latest
    container_name: rustart-minio
    ports:
      - "10000:9000"
      - "10001:10001"
    environment:
      - MINIO_ROOT_USER=rustart
      - MINIO_ROOT_PASSWORD=rustart123
    command: server /data --console-address ":10001"
    volumes:
      - rustart_minio_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # minio-setup:
  #   image: minio/mc:latest
  #   depends_on:
  #     - rustart-minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     mc alias set local http://localhost:10000 rustart rustart123 &&
  #     mc mb local/rustartminio || true &&
  #     mc ilm rule add local/rustartminio --expire-days 180
  #     mc anonymous set public rustart/rustartminio
  #     "

# networks:
#   rustart-network:
#     driver: bridge

volumes:
  rustart_postgres_data:
  rustart_minio_data:
